package com.chane.yfk.mybatis.mapper;

import com.chane.yfk.mybatis.model.YfkCUserCardTradeRecord;
import com.chane.yfk.mybatis.model.YfkCUserCardTradeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YfkCUserCardTradeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int countByExample(YfkCUserCardTradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int deleteByExample(YfkCUserCardTradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int insert(YfkCUserCardTradeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int insertSelective(YfkCUserCardTradeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    List<YfkCUserCardTradeRecord> selectByExample(YfkCUserCardTradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    YfkCUserCardTradeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YfkCUserCardTradeRecord record, @Param("example") YfkCUserCardTradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YfkCUserCardTradeRecord record, @Param("example") YfkCUserCardTradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YfkCUserCardTradeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user_card_trade_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YfkCUserCardTradeRecord record);
}