package com.chane.yfk.mybatis.dao;

import com.chane.yfk.mybatis.model.CUser;
import com.chane.yfk.mybatis.model.CUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    long countByExample(CUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    int deleteByExample(CUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    int insert(CUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    int insertSelective(CUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    List<CUser> selectByExample(CUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    CUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CUser record, @Param("example") CUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CUser record, @Param("example") CUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yfk_c_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CUser record);
}