package com.chane.yfk.mybatis.model;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_code
     *
     * @mbg.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_name
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.parent_area_code
     *
     * @mbg.generated
     */
    private String parentAreaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_level
     *
     * @mbg.generated
     */
    private String areaLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_code
     *
     * @return the value of area.area_code
     *
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_code
     *
     * @param areaCode the value for area.area_code
     *
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_name
     *
     * @return the value of area.area_name
     *
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_name
     *
     * @param areaName the value for area.area_name
     *
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.parent_area_code
     *
     * @return the value of area.parent_area_code
     *
     * @mbg.generated
     */
    public String getParentAreaCode() {
        return parentAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.parent_area_code
     *
     * @param parentAreaCode the value for area.parent_area_code
     *
     * @mbg.generated
     */
    public void setParentAreaCode(String parentAreaCode) {
        this.parentAreaCode = parentAreaCode == null ? null : parentAreaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_level
     *
     * @return the value of area.area_level
     *
     * @mbg.generated
     */
    public String getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_level
     *
     * @param areaLevel the value for area.area_level
     *
     * @mbg.generated
     */
    public void setAreaLevel(String areaLevel) {
        this.areaLevel = areaLevel == null ? null : areaLevel.trim();
    }
}