package com.chane.yfk.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class YfkCUserCardTradeRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.card_id
     *
     * @mbggenerated
     */
    private Long cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.trade_amount
     *
     * @mbggenerated
     */
    private BigDecimal tradeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.trade_count
     *
     * @mbggenerated
     */
    private Integer tradeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.trade_time
     *
     * @mbggenerated
     */
    private Date tradeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yfk_c_user_card_trade_record.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.id
     *
     * @return the value of yfk_c_user_card_trade_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.id
     *
     * @param id the value for yfk_c_user_card_trade_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.card_id
     *
     * @return the value of yfk_c_user_card_trade_record.card_id
     *
     * @mbggenerated
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.card_id
     *
     * @param cardId the value for yfk_c_user_card_trade_record.card_id
     *
     * @mbggenerated
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.card_no
     *
     * @return the value of yfk_c_user_card_trade_record.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.card_no
     *
     * @param cardNo the value for yfk_c_user_card_trade_record.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.card_type
     *
     * @return the value of yfk_c_user_card_trade_record.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.card_type
     *
     * @param cardType the value for yfk_c_user_card_trade_record.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.order_no
     *
     * @return the value of yfk_c_user_card_trade_record.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.order_no
     *
     * @param orderNo the value for yfk_c_user_card_trade_record.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.enterprise_id
     *
     * @return the value of yfk_c_user_card_trade_record.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.enterprise_id
     *
     * @param enterpriseId the value for yfk_c_user_card_trade_record.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.trade_type
     *
     * @return the value of yfk_c_user_card_trade_record.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.trade_type
     *
     * @param tradeType the value for yfk_c_user_card_trade_record.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.trade_amount
     *
     * @return the value of yfk_c_user_card_trade_record.trade_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.trade_amount
     *
     * @param tradeAmount the value for yfk_c_user_card_trade_record.trade_amount
     *
     * @mbggenerated
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.trade_count
     *
     * @return the value of yfk_c_user_card_trade_record.trade_count
     *
     * @mbggenerated
     */
    public Integer getTradeCount() {
        return tradeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.trade_count
     *
     * @param tradeCount the value for yfk_c_user_card_trade_record.trade_count
     *
     * @mbggenerated
     */
    public void setTradeCount(Integer tradeCount) {
        this.tradeCount = tradeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.trade_time
     *
     * @return the value of yfk_c_user_card_trade_record.trade_time
     *
     * @mbggenerated
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.trade_time
     *
     * @param tradeTime the value for yfk_c_user_card_trade_record.trade_time
     *
     * @mbggenerated
     */
    public void setTradeTime(Date tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yfk_c_user_card_trade_record.remark
     *
     * @return the value of yfk_c_user_card_trade_record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yfk_c_user_card_trade_record.remark
     *
     * @param remark the value for yfk_c_user_card_trade_record.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}